// Set a consistent date in the future for mock data
// Using January 2026 to match the provided schedule's context
const getFutureDate = (day: number, month: number = 0, year: number = 2026) => {
    // month is 0-indexed (0 for January)
    const date = new Date(Date.UTC(year, month, day, 21, 0, 0));
    return date.toISOString();
};

export const data = {
  "revisiones": [
    { 
      "id": "rev-trim-001", 
      "vehiculoId": "VEH-BAIXLLOB-201",
      "vehiculo": "201",
      "matricula": "0201MCD",
      "operador": "LA HISPANO IGUALADINA",
      "cochera": "Igualada",
      "tipo": "Preventiu Trimestral", 
      "hora": "21:00", 
      "fecha": getFutureDate(2, 0),
      "ubicacion": "C/ Lobatona 13", 
      "duracionEstimada": "45m", 
      "observaciones": "TORN NOCTURN - Inici any laboral",
      "prioridad": "Mitjana",
      "estado": "Pendent",
      "contract": "T-Mobilitat"
    },
    { 
      "id": "rev-trim-002", 
      "vehiculoId": "VEH-BAIXLLOB-202",
      "vehiculo": "202",
      "matricula": "0202NEF",
      "operador": "LA HISPANO IGUALADINA",
      "cochera": "Igualada",
      "tipo": "Preventiu Trimestral", 
      "hora": "21:45", 
      "fecha": getFutureDate(2, 0),
      "ubicacion": "C/ Lobatona 13", 
      "duracionEstimada": "45m", 
      "observaciones": "TORN NOCTURN - Inici any laboral",
      "prioridad": "Mitjana",
      "estado": "Pendent",
      "contract": "T-Mobilitat"
    },
    { 
      "id": "rev-trim-003", 
      "vehiculoId": "VEH-BAIXLLOB-203",
      "vehiculo": "203",
      "matricula": "0203PGH",
      "operador": "LA HISPANO IGUALADINA",
      "cochera": "Igualada",
      "tipo": "Preventiu Trimestral", 
      "hora": "22:30", 
      "fecha": getFutureDate(2, 0),
      "ubicacion": "C/ Lobatona 13", 
      "duracionEstimada": "45m", 
      "observaciones": "TORN NOCTURN - Inici any laboral",
      "prioridad": "Mitjana",
      "estado": "Completada",
      "contract": "T-Mobilitat"
    },
    { 
      "id": "rev-trim-004", 
      "vehiculoId": "VEH-BAIXLLOB-204",
      "vehiculo": "204",
      "operador": "LA HISPANO IGUALADINA",
      "cochera": "Igualada",
      "tipo": "Preventiu Trimestral", 
      "hora": "23:15", 
      "fecha": getFutureDate(2, 0),
      "ubicacion": "C/ Lobatona 13", 
      "duracionEstimada": "45m", 
      "observaciones": "TORN NOCTURN - Inici any laboral",
      "prioridad": "Mitjana",
      "estado": "Pendent",
      "contract": "T-Mobilitat"
    },
    { 
      "id": "rev-anual-001", 
      "vehiculoId": "VEH-BAIXLLOB-301",
      "vehiculo": "301",
      "operador": "CINTOT BUS",
      "cochera": "Sant Boi",
      "tipo": "Preventiu Anual", 
      "hora": "00:00", 
      "fecha": getFutureDate(2, 0),
      "ubicacion": "C/ Lobatona 13", 
      "duracionEstimada": "1h 30m", 
      "observaciones": "TORN NOCTURN - Inici any laboral",
      "prioridad": "Alta",
      "estado": "En Progrés",
      "contract": "T-Mobilitat"
    },
    { 
      "id": "corr-001", 
      "vehiculoId": "VEH-BAIXLLOB-303",
      "vehiculo": "303",
      "operador": "CINTOT BUS",
      "cochera": "Sant Boi",
      "tipo": "Correctiu", 
      "hora": "01:30", 
      "fecha": getFutureDate(2, 0),
      "ubicacion": "C/ Lobatona 13", 
      "duracionEstimada": "1h 30m", 
      "observaciones": "AVARIA: La validadora no respon. Possible problema d'alimentació.",
      "prioridad": "Crítica",
      "estado": "Pendent",
      "contract": "T-Mobilitat"
    },
     {
      "id": "inst-001",
      "vehiculoId": "VEH-TUSGSAL-101",
      "vehiculo": "101",
      "operador": "MOVENTIA L'HOSPITALET",
      "cochera": "Badalona",
      "tipo": "Instal·lació",
      "hora": "10:00",
      "fecha": getFutureDate(2, 0),
      "ubicacion": "Cotxera Badalona",
      "duracionEstimada": "30m",
      "observaciones": "Instal·lació completa de maquinari. No requereix configuració de programari.",
      "prioridad": "Mitjana",
      "estado": "Pendent",
      "contract": "T-Mobilitat"
    },
    {
      "id": "trasp-001",
      "vehiculoId": "VEH-SAGALES-501",
      "vehiculo": "501",
      "operador": "TRANSPORTS GENERALS D'OLESA",
      "cochera": "Granollers",
      "tipo": "Traspàs",
      "hora": "14:00",
      "fecha": getFutureDate(2, 0),
      "ubicacion": "Cotxera Granollers",
      "duracionEstimada": "30m",
      "observaciones": "Traspàs de validadora de vehicle antic a nou.",
      "prioridad": "Baixa",
      "estado": "Pendent",
      "contract": "T-Mobilitat"
    }
  ],
  "validadors_tasks": [
    {
      "id": "val-001",
      "contract": "C-4/2025",
      "operador": "MOVENTIA L'HOSPITALET",
      "cochera": "L'Hospitalet",
      "vehiculo": "5432",
      "matricula": "5432MBC",
      "n_validadora": "V-5432-1",
      "tipo": "Preventiu",
      "prioridad": "Normal",
      "distancia": "2.5km",
      "estimacion": "00:30",
      "turno": "Diurn",
      "estado": "Pendent",
      "hora": "09:30",
      "fecha": getFutureDate(2,0),
      "last_revision": "2025-10-15T10:00:00.000Z"
    },
    {
      "id": "val-002",
      "contract": "C-4/2025",
      "operador": "CINTOT BUS",
      "cochera": "Sant Boi",
      "vehiculo": "5433",
      "matricula": "5433NXY",
      "n_validadora": "V-5433-2",
      "tipo": "Correctiu",
      "prioridad": "Alta",
      "distancia": "3.5km",
      "estimacion": "01:00",
      "turno": "Diurn",
      "estado": "En curs",
      "hora": "11:00",
      "fecha": getFutureDate(2,0),
      "sla": "4h"
    },
    {
      "id": "val-003",
      "contract": "C-4/2025",
      "operador": "LA HISPANO IGUALADINA",
      "cochera": "Igualada",
      "vehiculo": "8102",
      "matricula": "8102PRT",
      "n_validadora": "V-8102-1",
      "tipo": "Extra",
      "prioridad": "Crítica",
      "distancia": "8.1km",
      "estimacion": "01:30",
      "turno": "Nocturn",
      "estado": "Pendent",
      "hora": "22:00",
      "fecha": getFutureDate(2,0)
    },
    {
      "id": "val-mag-001",
      "contract": "C-4/2025",
      "operador": "TRANSPORTS GENERALS D'OLESA",
      "cochera": "Olesa de Montserrat",
      "vehiculo": "101",
      "n_validadora": "MAG-101-1",
      "tipo": "Revisió Magnètica",
      "prioridad": "Normal",
      "distancia": "5.2km",
      "estimacion": "00:45",
      "turno": "Diurn",
      "estado": "Pendent",
      "hora": "12:00",
      "fecha": getFutureDate(2,0)
    },
    {
      "id": "val-mag-002",
      "contract": "C-4/2025",
      "operador": "MASATS TRANSPORTS GENERALS",
      "cochera": "Manresa",
      "vehiculo": "301",
      "n_validadora": "MAG-301-3",
      "tipo": "Revisió Magnètica",
      "prioridad": "Alta",
      "distancia": "1.5km",
      "estimacion": "00:45",
      "turno": "Nocturn",
      "estado": "Pendent",
      "hora": "23:00",
      "fecha": getFutureDate(2,0)
    },
    {
      "id": "val-mag-003",
      "contract": "C-4/2025",
      "operador": "AUTOCARES JULIÀ",
      "cochera": "El Prat",
      "vehiculo": "502",
      "n_validadora": "MAG-502-1",
      "tipo": "Revisió Magnètica",
      "prioridad": "Normal",
      "distancia": "15.7km",
      "estimacion": "01:00",
      "turno": "Dissabte",
      "estado": "Pendent",
      "hora": "10:00",
      "fecha": getFutureDate(4,0)
    },
    {
      "id": "c4-0001",
      "contract": "C-4/2025",
      "operador": "AUTOCARS DEL PENEDÈS",
      "cochera": "Vilafranca del Penedès",
      "vehiculo": "8102",
      "n_validadora": "VAL-112233",
      "tipo": "Preventiu",
      "prioridad": "Alta",
      "distancia": "1.2km",
      "estimacion": "01:30",
      "turno": "Nocturn",
      "estado": "Pendent",
      "hora": "08:30",
      "fecha": getFutureDate(2, 0)
    }
  ],
  "operadores": [
    { "id": "op-01", "nombre": "MOVENTIA L'HOSPITALET" },
    { "id": "op-02", "nombre": "CINTOT BUS" },
    { "id": "op-03", "nombre": "LA HISPANO IGUALADINA" },
    { "id": "op-04", "nombre": "TRANSPORTS GENERALS D'OLESA" },
    { "id": "op-05", "nombre": "MASATS TRANSPORTS GENERALS" },
    { "id": "op-06", "nombre": "HISPANO LLACUNENSE" },
    { "id": "op-07", "nombre": "AUTOCARES JULIÀ" },
    { "id": "op-08", "nombre": "AUTOCARS DEL PENEDÈS" },
    { "id": "op-09", "nombre": "UTE VALLDOREIX" }
  ],
  "autobuses": [
    { "id": "6916-HCR", "uniqueId": "VEH-ALSINA-300", "modelo": "Mercedes Citaro", "operadorId": "op-01" },
    { "id": "6917-HCR", "uniqueId": "VEH-ALSINA-301", "modelo": "Mercedes Citaro", "operadorId": "op-01" },
    { "id": "4444-HCR", "uniqueId": "VEH-ALSINA-445", "modelo": "Mercedes Citaro", "operadorId": "op-01" },
    { "id": "7001-HCR", "uniqueId": "VEH-JULIA-302", "modelo": "Mercedes Citaro", "operadorId": "op-07" },
    { "id": "7002-HCR", "uniqueId": "VEH-JULIA-303", "modelo": "Mercedes Citaro", "operadorId": "op-07" },
    { "id": "4602-JKD", "uniqueId": "VEH-PENEDES-326", "modelo": "Mercedes Citaro LE", "operadorId": "op-08" },
    { "id": "2223-JKD", "uniqueId": "VEH-PENEDES-204", "modelo": "Mercedes Citaro LE", "operadorId": "op-08" },
    { "id": "4192-KFL", "uniqueId": "VEH-PRAT-338", "modelo": "Otokar Vectio LE", "operadorId": "op-07" },
    { "id": "1111-KFL", "uniqueId": "VEH-PRAT-287", "modelo": "Otokar Vectio LE", "operadorId": "op-07" },
    { "id": "5400-LFN", "uniqueId": "VEH-FONT-342", "modelo": "Mercedes Citaro Hybrid", "operadorId": "op-05" },
    { "id": "5993-LMS", "uniqueId": "VEH-VENDRELL-344", "modelo": "Solaris Urbino 12 Hybrid", "operadorId": "op-06" },
    { "id": "3806-MBW", "uniqueId": "VEH-AUTOCORB-349", "modelo": "Solaris Urbino 12 Hybrid", "operadorId": "op-06" },
    { "id": "B-1234-CD", "uniqueId": "VEH-TUSGSAL-101", "modelo": "Mercedes Citaro", "operadorId": "op-01" },
    { "id": "B-5678-EF", "uniqueId": "VEH-TUSGSAL-102", "modelo": "Iveco Urbanway", "operadorId": "op-01" },
    { "id": "B-9012-GH", "uniqueId": "VEH-TUSGSAL-103", "modelo": "MAN Lion's City", "operadorId": "op-01" },
    { "id": "C-3456-IJ", "uniqueId": "VEH-BAIXLLOB-201", "modelo": "Mercedes Citaro Hybrid", "operadorId": "op-03" },
    { "id": "C-7890-KL", "uniqueId": "VEH-BAIXLLOB-202", "modelo": "Scania Citywide", "operadorId": "op-03" },
    { "id": "C-1111-IJ", "uniqueId": "VEH-BAIXLLOB-203", "modelo": "Mercedes Citaro Hybrid", "operadorId": "op-03" },
    { "id": "C-2222-KL", "uniqueId": "VEH-BAIXLLOB-204", "modelo": "Scania Citywide", "operadorId": "op-03" },
    { "id": "C-3333-IJ", "uniqueId": "VEH-BAIXLLOB-301", "modelo": "Mercedes Citaro Hybrid", "operadorId": "op-02" },
    { "id": "C-4444-KL", "uniqueId": "VEH-BAIXLLOB-302", "modelo": "Scania Citywide", "operadorId": "op-02" },
    { "id": "C-5555-IJ", "uniqueId": "VEH-BAIXLLOB-303", "modelo": "Mercedes Citaro Hybrid", "operadorId": "op-02" },
    { "id": "C-6666-KL", "uniqueId": "VEH-BAIXLLOB-304", "modelo": "Scania Citywide", "operadorId": "op-02" },
    { "id": "D-1122-MN", "uniqueId": "VEH-SAGALES-501", "modelo": "Volvo 7900", "operadorId": "op-04" },
    { "id": "D-3344-OP", "uniqueId": "VEH-SAGALES-502", "modelo": "Mercedes Citaro", "operadorId": "op-04" },
    { "id": "E-5566-QR", "uniqueId": "VEH-SOLER-601", "modelo": "MAN Lion's City Hybrid", "operadorId": "op-09" },
    { "id": "E-7788-ST", "uniqueId": "VEH-SOLER-602", "modelo": "Mercedes Citaro", "operadorId": "op-09" }
  ],
  "tecnicos": [
    { "id": "tec-01", "nombre": "A.P.U." }
  ],
  "eventosProximos": [
    {
      "id": "evt-001",
      "titulo": "Traspàs Programat",
      "fecha": getFutureDate(8, 0), // 8 de Gener
      "descripcion": "Traspàs programat a la Cotxera Nord",
      "operador": "LA HISPANO IGUALADINA",
      "ubicacion": "Cotxera Nord",
      "tipo": "Traspàs"
    }
  ]
};


    